dist:
  name: vunet-otelcol
  description: VuNet OpenTelemetry Collector Distribution
  version: 1.0.0
  output_path: ./_build
  otelcol_version: 0.64.1

receivers:
  - gomod: go.opentelemetry.io/collector/receiver/otlpreceiver v0.64.1
  - gomod: github.com/open-telemetry/opentelemetry-collector-contrib/receiver/hostmetricsreceiver v0.64.0

exporters:
  - gomod: go.opentelemetry.io/collector/exporter/loggingexporter v0.64.1
  - gomod: go.opentelemetry.io/collector/exporter/otlpexporter v0.64.1
  - gomod: go.opentelemetry.io/collector/exporter/otlphttpexporter v0.64.1

  - gomod: github.com/vunetsystems/opentelemetry-collector/exporter/kafkaexporter v1.0.0
  #- gomod: github.com/vunetsystems/opentelemetry-collector/exporter/vusmartmapsexporter v1.0.0
  # Should not use this --> - gomod: github.com/open-telemetry/opentelemetry-collector-contrib/exporter/kafkaexporter iv0.64.0

extensions:
  - gomod: go.opentelemetry.io/collector/extension/ballastextension v0.64.1
  - gomod: go.opentelemetry.io/collector/extension/zpagesextension v0.64.1
  - gomod: github.com/open-telemetry/opentelemetry-collector-contrib/extension/healthcheckextension v0.64.0

processors:
  - gomod: go.opentelemetry.io/collector/processor/batchprocessor v0.64.1
  - gomod: go.opentelemetry.io/collector/processor/memorylimiterprocessor v0.64.1
  - gomod: github.com/open-telemetry/opentelemetry-collector-contrib/processor/resourceprocessor v0.64.0
  - gomod: github.com/open-telemetry/opentelemetry-collector-contrib/processor/filterprocessor v0.64.0
  - gomod: github.com/open-telemetry/opentelemetry-collector-contrib/processor/tailsamplingprocessor v0.64.0

replaces:
  - github.com/vunetsystems/opentelemetry-collector/exporter/vusmartmapsexporter => ../../../exporter/vusmartmapsexporter
  - github.com/vunetsystems/opentelemetry-collector/exporter/kafkaexporter => ../../../exporter/vusmartmapsexporter
